name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-light.svg?color_snake=#374151&color_dots=#ffffff,#f3f4f6,#e5e7eb,#d1d5db,#9ca3af
            dist/github-snake-dark.svg?color_snake=#d1d5db&color_dots=#1f2937,#374151,#4b5563,#6b7280,#9ca3af

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}